package com.eximbills.invoice.rest;

import javax.enterprise.context.RequestScoped;
import javax.json.Json;
import javax.json.JsonArray;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;

@RequestScoped
@Path("invoice")
public class InvoiceResource {
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public JsonArray getProperties() throws ParseException {
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        JsonArray value = Json.createArrayBuilder()
                .add(Json.createObjectBuilder()
                        .add("maturityDate", "2017,01,1")
                        .add("faceValueInUSD", 1100.00)
                        .add("referenceNumber", "INV17000001"))
                .add(Json.createObjectBuilder()
                        .add("maturityDate", "2017,01,2")
                        .add("faceValueInUSD", 3200.00)
                        .add("referenceNumber", "INV17000002"))
                .add(Json.createObjectBuilder()
                        .add("maturityDate", "2017,01,2")
                        .add("faceValueInUSD", 1250.00)
                        .add("referenceNumber", "INV17000003"))
                .add(Json.createObjectBuilder()
                        .add("maturityDate", "2017,01,3")
                        .add("faceValueInUSD", 1280.00)
                        .add("referenceNumber", "INV17000004"))
                .add(Json.createObjectBuilder()
                        .add("maturityDate", "2017,01,4")
                        .add("faceValueInUSD", 1600.00)
                        .add("referenceNumber", "INV17000005"))
                .add(Json.createObjectBuilder()
                        .add("maturityDate", "2017,01,5")
                        .add("faceValueInUSD", 2200.00)
                        .add("referenceNumber", "INV17000006"))
                .add(Json.createObjectBuilder()
                        .add("maturityDate", "2017,01,6")
                        .add("faceValueInUSD", 2250.00)
                        .add("referenceNumber", "INV17000007"))
                .add(Json.createObjectBuilder()
                        .add("maturityDate", "2017,01,7")
                        .add("faceValueInUSD", 1200.00)
                        .add("referenceNumber", "INV17000008"))
                .add(Json.createObjectBuilder()
                        .add("maturityDate", "2017,01,8")
                        .add("faceValueInUSD", 1200.00)
                        .add("referenceNumber", "INV17000009"))
                .add(Json.createObjectBuilder()
                        .add("maturityDate", "2017,01,9")
                        .add("faceValueInUSD", 2560.00)
                        .add("referenceNumber", "INV17000010"))
                .add(Json.createObjectBuilder()
                        .add("maturityDate", "2017,01,10")
                        .add("faceValueInUSD", 3240.00)
                        .add("referenceNumber", "INV17000011"))
                .add(Json.createObjectBuilder()
                        .add("maturityDate", "2017,01,13")
                        .add("faceValueInUSD", 4200.00)
                        .add("referenceNumber", "INV17000012"))
                .add(Json.createObjectBuilder()
                        .add("maturityDate", "2017,01,18")
                        .add("faceValueInUSD", 1200.00)
                        .add("referenceNumber", "INV17000013"))
                .add(Json.createObjectBuilder()
                        .add("maturityDate", "2017,01,20")
                        .add("faceValueInUSD", 5200.00)
                        .add("referenceNumber", "INV17000014"))
                .add(Json.createObjectBuilder()
                        .add("maturityDate", "2017,01,23")
                        .add("faceValueInUSD", 2200.00)
                        .add("referenceNumber", "INV17000015"))
                .add(Json.createObjectBuilder()
                        .add("maturityDate", "2017,01,23")
                        .add("faceValueInUSD", 3200.00)
                        .add("referenceNumber", "INV17000016"))
                .add(Json.createObjectBuilder()
                        .add("maturityDate", "2017,01,23")
                        .add("faceValueInUSD", 1200.00)
                        .add("referenceNumber", "INV17000017"))
                .add(Json.createObjectBuilder()
                        .add("maturityDate", "2017,01,24")
                        .add("faceValueInUSD", 1200.00)
                        .add("referenceNumber", "INV17000018"))
                .add(Json.createObjectBuilder()
                        .add("maturityDate", "2017,01,25")
                        .add("faceValueInUSD", 5200.00)
                        .add("referenceNumber", "INV17000019"))
                .add(Json.createObjectBuilder()
                        .add("maturityDate", "2017,01,26")
                        .add("faceValueInUSD", 1200.00)
                        .add("referenceNumber", "INV17000020"))
                .add(Json.createObjectBuilder()
                        .add("maturityDate", "2017,01,27")
                        .add("faceValueInUSD", 1200.00)
                        .add("referenceNumber", "INV17000021"))
                .add(Json.createObjectBuilder()
                        .add("maturityDate", "2017,01,31")
                        .add("faceValueInUSD", 1200.00)
                        .add("referenceNumber", "INV17000022"))
                .add(Json.createObjectBuilder()
                        .add("maturityDate", "2017,02,1")
                        .add("faceValueInUSD", 5200.00)
                        .add("referenceNumber", "INV17000023"))
                .add(Json.createObjectBuilder()
                        .add("maturityDate", "2017,02,2")
                        .add("faceValueInUSD", 1200.00)
                        .add("referenceNumber", "INV17000024"))
                .add(Json.createObjectBuilder()
                        .add("maturityDate", "2017,02,3")
                        .add("faceValueInUSD", 1250.00)
                        .add("referenceNumber", "INV17000025"))
                .add(Json.createObjectBuilder()
                        .add("maturityDate", "2017,02,4")
                        .add("faceValueInUSD", 2500.00)
                        .add("referenceNumber", "INV17000026"))
                .add(Json.createObjectBuilder()
                        .add("maturityDate", "2017,02,5")
                        .add("faceValueInUSD", 1200.00)
                        .add("referenceNumber", "INV17000027"))
                .add(Json.createObjectBuilder()
                        .add("maturityDate", "2017,02,8")
                        .add("faceValueInUSD", 1200.00)
                        .add("referenceNumber", "INV17000028"))
                .add(Json.createObjectBuilder()
                        .add("maturityDate", "2017,02,9")
                        .add("faceValueInUSD", 1200.00)
                        .add("referenceNumber", "INV17000029"))
                .add(Json.createObjectBuilder()
                        .add("maturityDate", "2017,02,10")
                        .add("faceValueInUSD", 1200.00)
                        .add("referenceNumber", "INV17000030"))
                .build();

        return value;
    }
}